runtime: java17
env_variables:
  SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
  SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
  SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
  SPRING_SERVLET_MUTLIPART_ENABLED: $SPRING_SERVLET_MUTLIPART_ENABLED
  DO_SPACE_SECRET: $DO_SPACE_SECRET
  DO_SPACE_KEY: $DO_SPACE_KEY
  DO_SPACE_REGION: $DO_SPACE_REGION
  DO_SPACE_ENDPOINT: $DO_SPACE_ENDPOINT
  SPRING_MAIL_HOST: $SPRING_MAIL_HOST
  SPRING_MAIL_PORT: $SPRING_MAIL_PORT
  SPRING_MAIL_USERNAME: $SPRING_MAIL_USERNAME
  SPRING_MAIL_PASSWORD: $SPRING_MAIL_PASSWORD
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: $SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: $SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
  SPRING_REDIS_HOST: $SPRING_REDIS_HOST
  SPRING_REDIS_PORT: $SPRING_REDIS_PORT
  SPRING_REDIS_PASSWORD: $SPRING_REDIS_PASSWORD
