name: Release and deploy
on: 
  push:
    tags:
    - 'v*'
    - '!v*-alpha'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy_on_app_engine:
    needs: release
    name: Deploy to GAE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 73h/gae-app-yaml-replace-env-variables@v0.1
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_SERVLET_MUTLIPART_ENABLED: ${{ secrets.SPRING_SERVLET_MUTLIPART_ENABLED }}
          DO_SPACE_SECRET: ${{ secrets.DO_SPACE_SECRET }}
          DO_SPACE_KEY: ${{ secrets.DO_SPACE_KEY }}
          DO_SPACE_REGION: ${{ secrets.DO_SPACE_REGION }}
          DO_SPACE_ENDPOINT: ${{ secrets.DO_SPACE_ENDPOINT }}
          SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
          SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${{ secrets.SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH }}
          SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${{ secrets.SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE }}
        with:
          app_yaml_path: 'server/src/main/appengine/app.yaml'
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: 'server'
          deliverables: 'pom.xml'
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
  deploy_to_heroku:
    needs: deploy_on_app_engine
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Echo branch
      run: echo "Branch ${{ github.ref_name }}"
    - name: Deploy
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: ${{ github.ref_name }}
        appdir: "server" # <- This will point to the api folder in your project
